- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: golang setup
  ansible.builtin.import_role:
    name: common
    tasks_from: golang-setup

- name: service file setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup